/**
 * Isolated frontend mock data for the Job Application Tracker.
 * Replace this module with real API responses later — nothing here is
 * imported by presentation components directly (see jobTrackerApi.js).
 */

export const STATUSES = [
  'Saved',
  'Applied',
  'Online Assessment',
  'Interview',
  'Final Round',
  'Offer',
  'Rejected',
  'Withdrawn',
];

export const ACTIVE_STATUSES = ['Applied', 'Online Assessment', 'Interview', 'Final Round'];

export const STATUS_TONE = {
  Saved: 'neutral',
  Applied: 'primary',
  'Online Assessment': 'warning',
  Interview: 'accent',
  'Final Round': 'accent',
  Offer: 'success',
  Rejected: 'ember',
  Withdrawn: 'neutral',
};

export const EMPLOYMENT_TYPES = ['Full-time', 'Part-time', 'Internship', 'Contract'];

const day = (offset) => {
  const d = new Date();
  d.setHours(9, 0, 0, 0);
  d.setDate(d.getDate() + offset);
  return d.toISOString();
};

export const mockApplications = [
  {
    id: 'app-1',
    company: 'Google',
    role: 'Software Engineer II',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Interview',
    appliedDate: day(-5),
    updatedAt: day(-0.1),
    jobUrl: 'https://careers.google.com/jobs/results/12345',
    jobDescription:
      'Build and scale distributed backend services for Google Pay. Requires strong system design, Go/Java and large-scale data experience.',
    recruiterName: 'Ananya Rao',
    recruiterEmail: 'ananya.rao@google.com',
    recruiterLinkedin: 'https://linkedin.com/in/ananyarao',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'Referred by Karthik. Recruiter said the loop is 3 rounds + hiring manager.',
    nextAction: 'Technical Interview',
    nextActionDate: day(2),
    timeline: [
      { id: 't1', label: 'Saved', at: day(-9) },
      { id: 't2', label: 'Applied', at: day(-5) },
      { id: 't3', label: 'Online Assessment', at: day(-3) },
      { id: 't4', label: 'Interview', at: day(-0.1) },
    ],
  },
  {
    id: 'app-2',
    company: 'Stripe',
    role: 'Frontend Engineer',
    location: 'Remote (India)',
    employmentType: 'Full-time',
    status: 'Applied',
    appliedDate: day(-2),
    updatedAt: day(-1),
    jobUrl: 'https://stripe.com/jobs/listing/frontend-engineer',
    jobDescription:
      'Own product surfaces in the Stripe Dashboard. React, TypeScript, design-systems thinking and a high bar for craft.',
    recruiterName: 'Marc Devlin',
    recruiterEmail: 'marc.devlin@stripe.com',
    recruiterLinkedin: 'https://linkedin.com/in/marcdevlin',
    resumeUsed: 'Frontend_Craft_v2.pdf',
    notes: 'Portfolio matters a lot here — mention the design system work.',
    nextAction: 'Follow up with recruiter',
    nextActionDate: day(4),
    timeline: [
      { id: 't1', label: 'Saved', at: day(-4) },
      { id: 't2', label: 'Applied', at: day(-2) },
    ],
  },
  {
    id: 'app-3',
    company: 'Amazon',
    role: 'SDE-1',
    location: 'Hyderabad',
    employmentType: 'Full-time',
    status: 'Online Assessment',
    appliedDate: day(-8),
    updatedAt: day(-2),
    jobUrl: 'https://amazon.jobs/en/jobs/998877',
    jobDescription:
      'Fulfilment technology org. DSA-heavy interview loop with leadership-principle behavioural rounds.',
    recruiterName: 'Priya Menon',
    recruiterEmail: 'priyam@amazon.com',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'OA link expires in 5 days. Practice graphs + LP stories.',
    nextAction: 'Complete online assessment',
    nextActionDate: day(1),
    timeline: [
      { id: 't1', label: 'Saved', at: day(-10) },
      { id: 't2', label: 'Applied', at: day(-8) },
      { id: 't3', label: 'Online Assessment', at: day(-2) },
    ],
  },
  {
    id: 'app-4',
    company: 'Razorpay',
    role: 'Product Engineer',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Final Round',
    appliedDate: day(-16),
    updatedAt: day(-3),
    jobUrl: 'https://razorpay.com/jobs/product-engineer',
    jobDescription: 'Full-stack product engineering on the payments dashboard.',
    recruiterName: 'Sneha Iyer',
    recruiterEmail: 'sneha@razorpay.com',
    recruiterLinkedin: 'https://linkedin.com/in/snehaiyer',
    resumeUsed: 'Fullstack_Product_v1.pdf',
    notes: 'Final round is with the VP of Engineering.',
    nextAction: 'Final round — VP Engineering',
    nextActionDate: day(6),
    timeline: [
      { id: 't1', label: 'Applied', at: day(-16) },
      { id: 't2', label: 'Interview', at: day(-9) },
      { id: 't3', label: 'Final Round', at: day(-3) },
    ],
  },
  {
    id: 'app-5',
    company: 'Zerodha',
    role: 'Backend Engineer',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Offer',
    appliedDate: day(-30),
    updatedAt: day(-4),
    jobUrl: 'https://zerodha.com/careers',
    jobDescription: 'Go services for trading infrastructure. Low-latency systems.',
    recruiterName: 'Vivek Nair',
    recruiterEmail: 'vivek@zerodha.com',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'Offer valid for 10 days. Negotiating base.',
    nextAction: 'Respond to offer',
    nextActionDate: day(3),
    timeline: [
      { id: 't1', label: 'Applied', at: day(-30) },
      { id: 't2', label: 'Interview', at: day(-20) },
      { id: 't3', label: 'Final Round', at: day(-10) },
      { id: 't4', label: 'Offer', at: day(-4) },
    ],
  },
  {
    id: 'app-6',
    company: 'Atlassian',
    role: 'Senior Frontend Engineer',
    location: 'Remote',
    employmentType: 'Full-time',
    status: 'Rejected',
    appliedDate: day(-25),
    updatedAt: day(-11),
    jobUrl: 'https://atlassian.com/careers/1122',
    jobDescription: 'Jira frontend platform team.',
    recruiterName: 'Holly Brant',
    recruiterEmail: 'hbrant@atlassian.com',
    recruiterLinkedin: '',
    resumeUsed: 'Frontend_Craft_v2.pdf',
    notes: 'Rejected after system design round — brush up on frontend architecture.',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-25) },
      { id: 't2', label: 'Interview', at: day(-16) },
      { id: 't3', label: 'Rejected', at: day(-11) },
    ],
  },
  {
    id: 'app-7',
    company: 'Notion',
    role: 'Product Designer Engineer',
    location: 'Remote (APAC)',
    employmentType: 'Contract',
    status: 'Saved',
    appliedDate: '',
    updatedAt: day(-1),
    jobUrl: 'https://notion.so/careers',
    jobDescription: 'Hybrid design-engineering role on the editor surface.',
    recruiterName: '',
    recruiterEmail: '',
    recruiterLinkedin: '',
    resumeUsed: '',
    notes: 'Need to tailor a design-leaning resume before applying.',
    nextAction: 'Tailor resume and apply',
    nextActionDate: day(2),
    timeline: [{ id: 't1', label: 'Saved', at: day(-1) }],
  },
  {
    id: 'app-8',
    company: 'Swiggy',
    role: 'SDE II — Platform',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Withdrawn',
    appliedDate: day(-40),
    updatedAt: day(-18),
    jobUrl: '',
    jobDescription: 'Platform reliability team.',
    recruiterName: 'Rahul Sethi',
    recruiterEmail: 'rahul.sethi@swiggy.in',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'Withdrew — comp band too low.',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-40) },
      { id: 't2', label: 'Withdrawn', at: day(-18) },
    ],
  },
  {
    id: 'app-9',
    company: 'Freshworks',
    role: 'Full Stack Engineer',
    location: 'Chennai',
    employmentType: 'Full-time',
    status: 'Interview',
    appliedDate: day(-12),
    updatedAt: day(-2),
    jobUrl: 'https://freshworks.com/careers/4455',
    jobDescription: 'CRM product engineering, Rails + React.',
    recruiterName: 'Deepak Subramanian',
    recruiterEmail: 'deepak.s@freshworks.com',
    recruiterLinkedin: 'https://linkedin.com/in/deepaks',
    resumeUsed: 'Fullstack_Product_v1.pdf',
    notes: 'Panel interview with two engineers.',
    nextAction: 'Panel interview',
    nextActionDate: day(5),
    timeline: [
      { id: 't1', label: 'Applied', at: day(-12) },
      { id: 't2', label: 'Online Assessment', at: day(-7) },
      { id: 't3', label: 'Interview', at: day(-2) },
    ],
  },
  {
    id: 'app-10',
    company: 'Postman',
    role: 'Frontend Engineer II',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Applied',
    appliedDate: day(-1),
    updatedAt: day(-1),
    jobUrl: 'https://postman.com/careers/778',
    jobDescription: 'API client surface, heavy React + Electron.',
    recruiterName: 'Nikita Shah',
    recruiterEmail: 'nikita@postman.com',
    recruiterLinkedin: '',
    resumeUsed: 'Frontend_Craft_v2.pdf',
    notes: 'Applied through referral portal.',
    nextAction: 'Follow up if no reply',
    nextActionDate: day(7),
    timeline: [{ id: 't1', label: 'Applied', at: day(-1) }],
  },
];

export const mockActivity = [
  { id: 'act-1', company: 'Google', message: 'Status changed → Interview', at: day(-0.1) },
  { id: 'act-2', company: 'Stripe', message: 'Application added', at: day(-1) },
  { id: 'act-3', company: 'Amazon', message: 'Status changed → Online Assessment', at: day(-2) },
  { id: 'act-4', company: 'Freshworks', message: 'Panel interview scheduled', at: day(-2) },
  { id: 'act-5', company: 'Razorpay', message: 'Status changed → Final Round', at: day(-3) },
  { id: 'act-6', company: 'Zerodha', message: 'Offer received', at: day(-4) },
  { id: 'act-7', company: 'Notion', message: 'Role saved for later', at: day(-6) },
  { id: 'act-8', company: 'Atlassian', message: 'Status changed → Rejected', at: day(-11) },
  {
    id: 'act-9',
    company: 'Postman',
    message: 'Resume attached: Frontend_Craft_v2.pdf',
    at: day(-12),
  },
  { id: 'act-10', company: 'Swiggy', message: 'Status changed → Withdrawn', at: day(-18) },
  { id: 'act-11', company: 'Amazon', message: 'Recruiter call completed', at: day(-20) },
  { id: 'act-12', company: 'Google', message: 'Application added', at: day(-9) },
];

/* ------------------------------------------------------------------ *
 * Insight-relevant context: resume/profile skills + outcome feedback.
 * Kept in the same mock module so the whole dataset stays replaceable.
 * ------------------------------------------------------------------ */

export const mockProfile = {
  name: 'Sourav',
  headline: 'Backend-leaning full-stack engineer',
  resumeName: 'Backend_SDE_v4.pdf',
  skills: [
    'Node.js',
    'PostgreSQL',
    'REST APIs',
    'JavaScript',
    'React',
    'TypeScript',
    'Express',
    'MongoDB',
    'Git',
    'Docker',
  ],
};

/**
 * Outcome / feedback enrichment. `employerFeedback` fields are treated as
 * EXPLICIT feedback by the insight engine; everything else is only ever used
 * for pattern detection, never as a stated rejection reason.
 */
const enrichment = {
  'app-1': {
    interviewFeedback:
      'Recruiter noted strong coding round; system design depth will be probed in round 3.',
    interviewFeedbackSource: 'employer',
  },
  'app-5': {
    outcome: 'Offer',
    offerLetter: 'Offer: Backend Engineer, Zerodha — Go/PostgreSQL trading services.',
    employerFeedback: 'Hiring manager: strongest candidate on API design and SQL depth.',
  },
  'app-6': {
    outcome: 'Rejected',
    rejectionMessage:
      'We moved forward with a candidate who had deeper large-scale frontend architecture experience.',
    employerFeedback:
      'Interviewer feedback: frontend system design answer lacked depth on rendering at scale.',
  },
};

Object.entries(enrichment).forEach(([id, extra]) => {
  const target = mockApplications.find((a) => a.id === id);
  if (target) Object.assign(target, extra);
});

/** Additional closed-out history so patterns are statistically meaningful. */
mockApplications.push(
  {
    id: 'app-11',
    company: 'Uber',
    role: 'Backend Engineer',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Rejected',
    appliedDate: day(-55),
    updatedAt: day(-44),
    jobUrl: '',
    jobDescription:
      'Distributed systems team. Kafka event pipelines, Kubernetes, gRPC and high-throughput services.',
    recruiterName: 'Meera Kulkarni',
    recruiterEmail: 'meera@uber.com',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'Struggled with the event-streaming design question.',
    outcome: 'Rejected',
    rejectionMessage: 'Thanks for your time — we are moving ahead with other candidates.',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-55) },
      { id: 't2', label: 'Interview', at: day(-48) },
      { id: 't3', label: 'Rejected', at: day(-44) },
    ],
  },
  {
    id: 'app-12',
    company: 'Confluent',
    role: 'Platform Engineer',
    location: 'Remote',
    employmentType: 'Full-time',
    status: 'Rejected',
    appliedDate: day(-62),
    updatedAt: day(-58),
    jobUrl: '',
    jobDescription:
      'Kafka-native streaming platform. Requires Kafka internals, Kubernetes operators and distributed systems fundamentals.',
    recruiterName: '',
    recruiterEmail: '',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'No response after resume screen.',
    outcome: 'Rejected',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-62) },
      { id: 't2', label: 'Rejected', at: day(-58) },
    ],
  },
  {
    id: 'app-13',
    company: 'Cred',
    role: 'Backend Engineer',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Offer',
    appliedDate: day(-70),
    updatedAt: day(-52),
    jobUrl: '',
    jobDescription:
      'Node.js and PostgreSQL services powering rewards. REST APIs, Redis caching, clean API design.',
    recruiterName: 'Aditi Verma',
    recruiterEmail: 'aditi@cred.club',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'Declined — timing.',
    outcome: 'Offer',
    employerFeedback: 'Panel: excellent Node.js/PostgreSQL depth, pragmatic API design.',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-70) },
      { id: 't2', label: 'Interview', at: day(-62) },
      { id: 't3', label: 'Offer', at: day(-52) },
    ],
  },
  {
    id: 'app-14',
    company: 'Hasura',
    role: 'SDE-1',
    location: 'Remote (India)',
    employmentType: 'Full-time',
    status: 'Rejected',
    appliedDate: day(-80),
    updatedAt: day(-68),
    jobUrl: '',
    jobDescription:
      'GraphQL engine internals. Kubernetes deployment, distributed systems and observability.',
    recruiterName: '',
    recruiterEmail: '',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'Rejected after take-home.',
    outcome: 'Rejected',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-80) },
      { id: 't2', label: 'Online Assessment', at: day(-74) },
      { id: 't3', label: 'Rejected', at: day(-68) },
    ],
  },
  {
    id: 'app-15',
    company: 'Groww',
    role: 'SDE-1',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Offer',
    appliedDate: day(-95),
    updatedAt: day(-78),
    jobUrl: '',
    jobDescription:
      'Node.js REST APIs with PostgreSQL for investing products. Strong SQL and API design.',
    recruiterName: 'Nishant Roy',
    recruiterEmail: 'nishant@groww.in',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'Offer received, chose to continue searching.',
    outcome: 'Offer',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-95) },
      { id: 't2', label: 'Interview', at: day(-88) },
      { id: 't3', label: 'Offer', at: day(-78) },
    ],
  },
  {
    id: 'app-16',
    company: 'Dream11',
    role: 'Senior Frontend Engineer',
    location: 'Mumbai',
    employmentType: 'Full-time',
    status: 'Rejected',
    appliedDate: day(-100),
    updatedAt: day(-90),
    jobUrl: '',
    jobDescription:
      'High-scale React frontend. Micro-frontends, performance budgets, frontend architecture at scale.',
    recruiterName: '',
    recruiterEmail: '',
    recruiterLinkedin: '',
    resumeUsed: 'Frontend_Craft_v2.pdf',
    notes: 'Rejected at architecture round.',
    outcome: 'Rejected',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-100) },
      { id: 't2', label: 'Interview', at: day(-94) },
      { id: 't3', label: 'Rejected', at: day(-90) },
    ],
  },
  {
    id: 'app-17',
    company: 'Flipkart',
    role: 'Backend Engineer',
    location: 'Bangalore',
    employmentType: 'Full-time',
    status: 'Rejected',
    appliedDate: day(-110),
    updatedAt: day(-101),
    jobUrl: '',
    jobDescription:
      'Order platform. Kafka streams, Kubernetes, distributed systems and system design depth required.',
    recruiterName: '',
    recruiterEmail: '',
    recruiterLinkedin: '',
    resumeUsed: 'Backend_SDE_v4.pdf',
    notes: 'System design round was the blocker in my own assessment.',
    outcome: 'Rejected',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-110) },
      { id: 't2', label: 'Interview', at: day(-105) },
      { id: 't3', label: 'Rejected', at: day(-101) },
    ],
  },
  {
    id: 'app-18',
    company: 'Zoho',
    role: 'Full Stack Engineer',
    location: 'Chennai',
    employmentType: 'Full-time',
    status: 'Rejected',
    appliedDate: day(-120),
    updatedAt: day(-112),
    jobUrl: '',
    jobDescription: 'Java + React product engineering with REST APIs and MySQL.',
    recruiterName: '',
    recruiterEmail: '',
    recruiterLinkedin: '',
    resumeUsed: 'Fullstack_Product_v1.pdf',
    notes: '',
    outcome: 'Rejected',
    nextAction: '',
    nextActionDate: '',
    timeline: [
      { id: 't1', label: 'Applied', at: day(-120) },
      { id: 't2', label: 'Rejected', at: day(-112) },
    ],
  },
);
