apiVersion: v1
kind: ConfigMap
metadata:
  name: quickai-config
data:
  PORT: '3000'
  NODE_ENV: 'production'
  FRONTEND_ORIGIN: 'https://d30jzk0hgtqxk3.cloudfront.net'
  REDIS_URL: 'redis://quickai-redis:6379'
