/**
 * Demo Fallback Content
 * ---------------------
 * When API keys are exhausted or services are down, the app returns
 * high-quality pre-written content so recruiters/interviewers always
 * see a fully working product.
 *
 * Each response includes `demo: true` so the client can show a subtle
 * "Demo Mode" indicator for transparency.
 */

// ─── Article Fallbacks (keyed by approximate length) ─────────────────────────

const articleFallbacks = {
  short: `# The Future of Artificial Intelligence

Artificial Intelligence (AI) is no longer a futuristic concept — it's reshaping our world in real-time. From healthcare diagnostics to autonomous vehicles, AI systems are becoming integral to modern life.

## Current Landscape

Today's AI landscape is dominated by **Large Language Models (LLMs)** and **generative AI**. Companies like OpenAI, Google DeepMind, and Anthropic are pushing the boundaries of what machines can understand and create. These models can write code, compose music, generate images, and even engage in nuanced conversations.

## Impact on Industries

- **Healthcare**: AI-powered diagnostics can detect diseases like cancer with accuracy surpassing human radiologists. Drug discovery timelines have been reduced from years to months.
- **Finance**: Algorithmic trading, fraud detection, and personalized banking are now AI-driven.
- **Education**: Adaptive learning platforms tailor content to individual student needs, democratizing quality education.
- **Creative Arts**: Tools like DALL-E and Midjourney enable anyone to create stunning visual art from text descriptions.

## Ethical Considerations

With great power comes great responsibility. Key concerns include:
- **Bias in AI systems** that can perpetuate societal inequalities
- **Job displacement** as automation replaces routine tasks
- **Privacy concerns** with facial recognition and surveillance
- **Misinformation** generated by deepfakes and AI-written content

## Looking Ahead

The next decade will likely see AI become even more embedded in daily life. **Agentic AI** — systems that can autonomously plan and execute complex tasks — represents the next frontier. As AI grows more capable, the importance of responsible development, transparent governance, and human oversight cannot be overstated.

The future of AI isn't about replacing humans — it's about augmenting human capabilities and solving problems that were previously intractable. The question isn't whether AI will transform our world, but how we choose to guide that transformation.`,

  medium: `# How AI is Revolutionizing Modern Software Development

The software development industry is undergoing a seismic shift, driven by the rapid advancement of artificial intelligence technologies. What once seemed like science fiction — machines writing code, debugging programs, and architecting systems — is now an everyday reality for developers worldwide.

## The Rise of AI-Powered Development Tools

### Code Generation and Completion
AI-powered code assistants like GitHub Copilot, Cursor, and Amazon CodeWhisperer have fundamentally changed how developers write code. These tools leverage large language models trained on billions of lines of code to provide intelligent suggestions, complete entire functions, and even generate boilerplate code from natural language descriptions.

Studies show that developers using AI assistants complete tasks **55% faster** on average, with significant improvements in both productivity and code quality. This isn't about replacing developers — it's about amplifying their capabilities.

### Automated Testing
AI is transforming quality assurance by automatically generating test cases, identifying edge cases that human testers might miss, and predicting which parts of a codebase are most likely to contain bugs. Tools like Diffblue Cover can generate unit tests for Java code with high coverage, reducing the manual testing burden significantly.

### Intelligent Code Review
AI-powered code review tools can detect security vulnerabilities, performance bottlenecks, and code style inconsistencies in real-time. These tools go beyond simple linting — they understand context, design patterns, and best practices to provide meaningful feedback.

## Impact on the Development Lifecycle

### Planning and Architecture
AI tools are now capable of analyzing project requirements and suggesting architectural patterns. By examining similar projects and codebases, these systems can recommend technology stacks, database schemas, and API designs that align with best practices.

### Development Speed
The combination of AI code generation, intelligent autocomplete, and automated refactoring has dramatically reduced development time. What previously took weeks can now be accomplished in days, allowing teams to iterate faster and deliver value sooner.

### Maintenance and DevOps
AI-driven monitoring systems can predict infrastructure failures before they occur, automatically scale resources based on usage patterns, and even self-heal common issues. This proactive approach to operations reduces downtime and improves system reliability.

## Challenges and Considerations

Despite the remarkable benefits, AI in software development comes with challenges:

- **Code Quality Concerns**: AI-generated code may contain subtle bugs or security vulnerabilities that pass initial review
- **Over-Reliance**: Developers may lose fundamental skills if they rely too heavily on AI suggestions
- **Intellectual Property**: Questions about code ownership and licensing remain unresolved
- **Bias in Suggestions**: AI models trained on existing code may perpetuate outdated patterns and practices

## The Future of AI-Augmented Development

Looking ahead, we can expect:
1. **More sophisticated AI agents** that can handle entire features end-to-end
2. **Natural language programming** where non-technical users can build applications through conversation
3. **AI-driven architecture optimization** that continuously improves system performance
4. **Collaborative AI** that works alongside development teams as a virtual team member

## Conclusion

AI is not replacing software developers — it's evolving the role. The developers who thrive in this new landscape will be those who learn to effectively collaborate with AI tools, leveraging them as force multipliers while maintaining their critical thinking and creative problem-solving skills. The future belongs to the human-AI partnership, where each brings unique strengths to the table.`,

  long: `# The Comprehensive Guide to Building Scalable Web Applications with Modern Architecture

Building scalable web applications is one of the most critical challenges facing software engineering teams today. As user bases grow from hundreds to millions, the architectural decisions made early in a project's lifecycle can determine its success or failure. This comprehensive guide explores modern approaches to building applications that scale gracefully.

## Understanding Scalability

Scalability is the ability of a system to handle increased load without degrading performance. There are two primary types:

### Vertical Scaling (Scale Up)
Adding more resources (CPU, RAM, storage) to a single server. This approach is simple but has physical limits and creates a single point of failure.

### Horizontal Scaling (Scale Out)
Adding more servers to distribute the load. This is the preferred approach for modern web applications as it offers theoretically unlimited scaling potential.

## Modern Architecture Patterns

### Microservices Architecture
Breaking down a monolithic application into smaller, independently deployable services. Each service owns its data and business logic, communicating with other services through well-defined APIs.

**Benefits:**
- Independent deployment and scaling
- Technology flexibility per service
- Fault isolation
- Team autonomy

**Challenges:**
- Distributed system complexity
- Data consistency across services
- Network latency
- Operational overhead

### Event-Driven Architecture
Services communicate through events rather than direct API calls. This creates loose coupling and enables real-time processing.

Key components include:
- **Event Producers**: Services that emit events when state changes occur
- **Event Brokers**: Systems like Apache Kafka or RabbitMQ that manage event routing
- **Event Consumers**: Services that react to events

### Serverless Architecture
Running code without managing servers. Cloud providers handle infrastructure, scaling, and availability automatically.

Popular serverless platforms include AWS Lambda, Google Cloud Functions, and Azure Functions. This model is particularly cost-effective for applications with variable workloads.

## Database Strategies for Scale

### Relational Databases
PostgreSQL and MySQL remain excellent choices for many applications. Key scaling strategies include:
- **Read Replicas**: Distribute read queries across multiple database instances
- **Connection Pooling**: Reduce the overhead of database connections using tools like PgBouncer
- **Partitioning**: Split large tables into smaller, more manageable pieces

### NoSQL Databases
For specific use cases, NoSQL databases offer superior scalability:
- **MongoDB**: Document store ideal for flexible schemas
- **Redis**: In-memory key-value store perfect for caching and real-time features
- **Cassandra**: Wide-column store designed for write-heavy workloads

### Caching Strategies
Implementing multiple caching layers dramatically improves performance:
1. **Browser Cache**: Static assets cached on the client
2. **CDN Cache**: Content distributed globally for low-latency access
3. **Application Cache**: In-memory caches (Redis, Memcached) for frequently accessed data
4. **Database Cache**: Query result caching at the database level

## Frontend Performance Optimization

### Code Splitting
Loading only the JavaScript needed for the current page view, reducing initial bundle size.

### Server-Side Rendering (SSR)
Rendering pages on the server for faster initial load times and better SEO. Frameworks like Next.js and Nuxt.js make this straightforward.

### Progressive Web Apps (PWAs)
Combining the best of web and mobile apps with offline capabilities, push notifications, and app-like experiences.

### Image Optimization
- Use modern formats like WebP and AVIF
- Implement lazy loading for below-the-fold images
- Use responsive images with srcset for different screen sizes

## API Design Best Practices

### RESTful APIs
Following REST principles for predictable, resource-oriented APIs:
- Use appropriate HTTP methods (GET, POST, PUT, DELETE)
- Implement proper status codes
- Version your APIs
- Use pagination for large datasets

### GraphQL
An alternative to REST that allows clients to request exactly the data they need:
- Reduces over-fetching and under-fetching
- Strong type system
- Single endpoint
- Real-time subscriptions

### API Gateway Pattern
A single entry point for all client requests that handles:
- Authentication and authorization
- Rate limiting
- Request routing
- Response transformation
- Monitoring and logging

## Security Considerations

### Authentication and Authorization
- Implement OAuth 2.0 / OpenID Connect
- Use JWT tokens with proper expiration
- Apply the principle of least privilege
- Enable multi-factor authentication

### Data Protection
- Encrypt data at rest and in transit
- Implement proper input validation
- Use parameterized queries to prevent SQL injection
- Apply Content Security Policy (CSP) headers

## Monitoring and Observability

### The Three Pillars
1. **Logs**: Structured logging with tools like ELK Stack or Loki
2. **Metrics**: System and application metrics with Prometheus and Grafana
3. **Traces**: Distributed tracing with Jaeger or Zipkin

### Health Checks and Alerting
- Implement health check endpoints for each service
- Configure alerts for critical metrics
- Use runbooks for common incident scenarios
- Practice incident response regularly

## Conclusion

Building scalable web applications requires careful consideration of architecture, data management, performance optimization, and operational practices. The key is to start with a solid foundation and evolve your architecture as your application grows. Remember: premature optimization is the root of all evil, but planning for scale from the beginning is wisdom.

The most successful teams combine modern architecture patterns with pragmatic engineering practices, always keeping the end user experience at the center of their decisions.`,
};

// ─── Blog Title Fallbacks ────────────────────────────────────────────────────

const blogTitleFallbacks = [
  `Here are 5 catchy and attractive blog titles:

1. **"From Zero to Hero: How AI is Turning Everyday People Into Content Creators"**
2. **"The Silent Revolution: Why AI Will Change More Jobs Than the Internet Did"**
3. **"10 AI Tools That Will Make You 10x More Productive (And Most Are Free)"**
4. **"Why Your Next Best Friend Might Be an AI — And That's Perfectly OK"**
5. **"The AI Playbook: How Smart Companies Are Quietly Dominating Their Industries"**`,

  `Here are 5 catchy and attractive blog titles:

1. **"Stop Scrolling, Start Creating: The Ultimate Guide to AI-Powered Productivity"**
2. **"The Future is Now: 7 Ways AI is Already Changing Your Daily Life"**
3. **"Beginner's Guide to AI: Everything You Need to Know (But Were Afraid to Ask)"**
4. **"How I Built a Side Hustle Using Nothing But AI Tools — A Step-by-Step Story"**
5. **"The Great Debate: Will AI Replace Developers or Make Them Unstoppable?"**`,

  `Here are 5 catchy and attractive blog titles:

1. **"Code Like a Senior Developer — Using AI as Your Pair Programmer"**
2. **"The Hidden Cost of Ignoring AI: What Every Business Owner Needs to Know"**
3. **"From Prompt to Product: Building Real Applications with Generative AI"**
4. **"Why the Best Time to Learn AI Was Yesterday (And the Second Best Is Today)"**
5. **"The Art of the Prompt: Mastering AI Communication for Better Results"**`,
];

// ─── Resume Review Fallback ──────────────────────────────────────────────────

const resumeReviewFallback = `## Resume Review Summary

### Strengths ✅

1. **Clear Structure**: The resume follows a well-organized format with distinct sections for experience, education, and skills, making it easy for recruiters to scan quickly.

2. **Quantified Achievements**: Good use of metrics and numbers to demonstrate impact (e.g., percentages, user counts, revenue figures). This adds credibility to your accomplishments.

3. **Relevant Technical Skills**: The skills section showcases in-demand technologies that align well with current market requirements. Your technology stack is modern and comprehensive.

4. **Strong Action Verbs**: Effective use of action verbs like "developed," "implemented," "optimized," and "led" to describe responsibilities and achievements.

### Areas for Improvement 🔧

1. **Professional Summary**: Consider adding a 2-3 line professional summary at the top that highlights your unique value proposition and career objectives.

2. **Project Impact**: While you list responsibilities well, try to include more specific outcomes. For example, instead of "improved performance," say "improved page load speed by 40%, reducing bounce rate by 15%."

3. **Soft Skills**: The resume could benefit from demonstrating leadership, communication, and collaboration skills through your experience descriptions rather than just listing them.

4. **ATS Optimization**: Ensure your resume includes relevant keywords from job descriptions you're targeting. Many companies use Applicant Tracking Systems that filter resumes based on keyword matches.

### Overall Score: **7.5/10**

This is a solid resume that demonstrates technical competence. With the suggested improvements, particularly around quantifying impact and adding a professional summary, this could easily become a 9/10 resume.`;

// ─── Image Fallbacks (pre-hosted sample images) ─────────────────────────────

const imageFallbacks = [
  'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/nature-mountains',
  'https://res.cloudinary.com/demo/image/upload/v1/samples/animals/cat',
  'https://res.cloudinary.com/demo/image/upload/v1/samples/landscapes/architecture-signs',
  'https://res.cloudinary.com/demo/image/upload/v1/samples/food/dessert',
  'https://res.cloudinary.com/demo/image/upload/v1/samples/people/smiling-man',
];

// ─── Helper Functions ────────────────────────────────────────────────────────

/**
 * Returns a demo article based on requested length.
 */
export function getDemoArticle(length = 800) {
  if (length <= 800) return articleFallbacks.short;
  if (length <= 1200) return articleFallbacks.medium;
  return articleFallbacks.long;
}

/**
 * Returns random demo blog titles.
 */
export function getDemoBlogTitles() {
  return blogTitleFallbacks[Math.floor(Math.random() * blogTitleFallbacks.length)];
}

/**
 * Returns a demo resume review.
 */
export function getDemoResumeReview() {
  return resumeReviewFallback;
}

/**
 * Returns a random demo image URL.
 */
export function getDemoImage() {
  return imageFallbacks[Math.floor(Math.random() * imageFallbacks.length)];
}

/**
 * Check if an error is an API quota/key exhaustion error.
 */
export function isQuotaError(error) {
  const msg = (error?.message || '').toLowerCase();
  const status = error?.response?.status || error?.status;
  return (
    status === 429 ||
    status === 402 ||
    status === 403 ||
    msg.includes('quota') ||
    msg.includes('rate limit') ||
    msg.includes('exceeded') ||
    msg.includes('exhausted') ||
    msg.includes('billing') ||
    msg.includes('payment') ||
    msg.includes('insufficient') ||
    msg.includes('api key') ||
    msg.includes('unauthorized') ||
    msg.includes('too many requests')
  );
}
